BEGIN;
ALTER TABLE blocks
  ALTER COLUMN block_gaslimit TYPE BIGINT USING block_gaslimit :: BIGINT;

ALTER TABLE blocks
  ALTER COLUMN block_gasused TYPE BIGINT USING block_gasused :: BIGINT;

ALTER TABLE blocks
  ALTER COLUMN block_time TYPE BIGINT USING block_time :: BIGINT;

ALTER TABLE blocks
  ALTER COLUMN block_reward TYPE DOUBLE PRECISION USING block_time :: DOUBLE PRECISION;

ALTER TABLE blocks
  ALTER COLUMN block_uncles_reward TYPE DOUBLE PRECISION USING block_time :: DOUBLE PRECISION;

COMMIT;
