dist: trusty
language: go
go:
  - 1.9
services:
  - postgresql
addons:
  postgresql: "9.6"

go_import_path: github.com/vulcanize/vulcanizedb

before_install:
  # ginkgo golint dep migrate
  - make installtools
  # geth
  - wget https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-1.7.2-1db4ecdc.tar.gz
  - tar -xzf geth-linux-amd64-1.7.2-1db4ecdc.tar.gz
  - sudo cp geth-linux-amd64-1.7.2-1db4ecdc/geth /usr/local/bin

before_script:
  - sudo -u postgres createdb vulcanize_private
  - make migrate HOST_NAME=localhost NAME=vulcanize_private PORT=5432
  - make createprivate
  - nohup make startprivate </dev/null &

script:
  - make test

notifications:
  email: false
