dist: trusty
language: go
go:
  - 1.9
services:
  - postgresql
addons:
  postgresql: "9.6"

go_import_path: github.com/vulcanize/vulcanizedb

before_install:
  # ginkgo
  - go get -u github.com/onsi/ginkgo/ginkgo
  # migrate
  - go get -u -d github.com/mattes/migrate/cli github.com/lib/pq
  - sudo $(which go) build -tags 'postgres' -o /usr/local/bin/migrate github.com/mattes/migrate/cli
  - sudo -u postgres createdb vulcanize_private
  # geth
  - wget https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-1.7.2-1db4ecdc.tar.gz
  - tar -xzf geth-linux-amd64-1.7.2-1db4ecdc.tar.gz
  - sudo cp geth-linux-amd64-1.7.2-1db4ecdc/geth /usr/local/bin

before_script:
  - ./scripts/setup
  - nohup ./scripts/start_private_blockchain </dev/null &
  - make migrate HOST_NAME=localhost NAME=vulcanize_private PORT=5432

script:
  - ginkgo -r

notifications:
  email: false
