dist: trusty
language: go
go:
  - 1.9
services:
  - postgresql
addons:
  postgresql: "9.6"

go_import_path: github.com/vulcanize/vulcanizedb

before_install:
  # ginkgo golint dep migrate
  - make installtools
  - bash ./scripts/install-postgres-10.sh

before_script:
  - sudo -u postgres createdb vulcanize_private
  - make migrate NAME=vulcanize_private

script:
  - make test

notifications:
  email: false
