
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "gopkg.in/fsnotify/fsnotify.v1"

[[override]]
  name = "github.com/pressly/sup"
  version = "0.5.3"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.2.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  source = "github.com/vulcanize/go-ethereum"
  branch = "rpc_statediffing"

[[constraint]]
  name = "github.com/vulcanize/eth-block-extractor"
  branch = "pair_with_syncAndPublish"

[[override]]
  name = "github.com/ipfs/go-ipfs"
  version = "0.4.20"

[[override]]
  name = "github.com/ipfs/go-ds-badger"
  version = "0.0.3"

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "github.com/ethereum/go-ethereum"
    unused-packages = false

  [[prune.project]]
    name = "github.com/karalabe/hid"
    unused-packages = false
