[database]
    name     = "vulcanize_public"
    hostname = "localhost"
    user     = "vulcanize"
    password = "vulcanize"
    port     = 5432

[client]
    ipcPath  = "http://kovan0.vulcanize.io:8545"

[datadog]
    name     = "maker_vdb_staging"

[exporter]
    name     = "storageTransformerExporter"
    save     = false
    transformerNames = [
        "pit",
        "vat",
        "vow"
    ]
    [exporter.pit]
        path = "transformers/storage_diffs/maker/pit/initializer"
        type = "eth_storage"
        repository = "github.com/vulcanize/mcd_transformers"
        migrations = "db/migrations"
    [exporter.vat]
        path = "transformers/storage_diffs/maker/vat/initializer"
        type = "eth_storage"
        repository = "github.com/vulcanize/mcd_transformers"
        migrations = "db/migrations"
    [exporter.vow]
        path = "transformers/storage_diffs/maker/vow/initializer"
        type = "eth_storage"
        repository = "github.com/vulcanize/mcd_transformers"
        migrations = "db/migrations"

[filesystem]
    storageDiffsPath = "INSERT-PATH-TO-STORAGE-DIFFS"

[contract]
    [contract.address]
            pit      = "0xe7cf3198787c9a4daac73371a38f29aaeeced87e"
            vat      = "0xcd726790550afcd77e9a7a47e86a3f9010af126b"
            vow      = "0x3728e9777B2a0a611ee0F89e00E01044ce4736d1"
