[database]
    name     = "vulcanize_public"
    hostname = "localhost"
    port     = 5432

[client]
    ipcPath  = "ws://127.0.0.1:8546"
    ipfsPath = "/Users/iannorden/.ipfs"

[server]
    ipcPath = "/Users/iannorden/.vulcanize/vulcanize.ipc"
    wsEndpoint = "127.0.0.1:80"
