package constants

var (
	BiteLabel                = "bite"
	CatFileChopLumpLabel     = "catFileChopLump"
	CatFileFlipLabel         = "catFileFlip"
	CatFilePitVowLabel       = "catFilePitVow"
	DealLabel                = "deal"
	DentLabel                = "dent"
	DripDripLabel            = "dripDrip"
	DripFileIlkLabel         = "dripFileIlk"
	DripFileRepoLabel        = "dripFileRepo"
	DripFileVowLabel         = "dripFileVow"
	FlapKickLabel            = "flapKick"
	FlipKickLabel            = "flipKick"
	FlopKickLabel            = "flopKick"
	FrobLabel                = "frob"
	PitFileDebtCeilingLabel  = "pitFileDebtCeiling"
	PitFileIlkLabel          = "pitFileIlk"
	PitFileStabilityFeeLabel = "pitFileStabilityFee"
	PriceFeedLabel           = "priceFeed"
	TendLabel                = "tend"
	VatFluxLabel             = "vatFlux"
	VatFoldLabel             = "vatFold"
	VatGrabLabel             = "vatGrab"
	VatHealLabel             = "vatHeal"
	VatInitLabel             = "vatInit"
	VatMoveLabel             = "vatMove"
	VatSlipLabel             = "vatSlip"
	VatTollLabel             = "vatToll"
	VatTuneLabel             = "vatTune"
	VowFlogLabel             = "vowFlog"
)
