package constants

var (
	BiteSignature               = GetEventSignature(biteMethod)
	CatFileChopLumpSignature    = GetLogNoteSignature(catFileChopLumpMethod)
	CatFileFlipSignature        = GetLogNoteSignature(catFileFlipMethod)
	CatFilePitVowSignature      = GetLogNoteSignature(catFilePitVowMethod)
	DealSignature               = GetLogNoteSignature(dealMethod)
	DentFunctionSignature       = GetLogNoteSignature(dentMethod)
	DripDripSignature           = GetLogNoteSignature(dripDripMethod)
	DripFileIlkSignature        = GetLogNoteSignature(dripFileIlkMethod)
	DripFileRepoSignature       = GetLogNoteSignature(dripFileRepoMethod)
	DripFileVowSignature        = GetLogNoteSignature(dripFileVowMethod)
	FlapKickSignature           = GetEventSignature(flapKickMethod)
	FlipKickSignature           = GetEventSignature(flipKickMethod)
	FlopKickSignature           = GetEventSignature(flopKickMethod)
	FrobSignature               = GetEventSignature(frobMethod)
	LogValueSignature           = GetEventSignature(logValueMethod)
	PitFileDebtCeilingSignature = GetLogNoteSignature(pitFileDebtCeilingMethod)
	PitFileIlkSignature         = GetLogNoteSignature(pitFileIlkMethod)
	TendFunctionSignature       = GetLogNoteSignature(tendMethod)
	VatFluxSignature            = GetLogNoteSignature(vatFluxMethod)
	VatFoldSignature            = GetLogNoteSignature(vatFoldMethod)
	VatGrabSignature            = GetLogNoteSignature(vatGrabMethod)
	VatHealSignature            = GetLogNoteSignature(vatHealMethod)
	VatInitSignature            = GetLogNoteSignature(vatInitMethod)
	VatMoveSignature            = GetLogNoteSignature(vatMoveMethod)
	VatSlipSignature            = GetLogNoteSignature(vatSlipMethod)
	VatTollSignature            = GetLogNoteSignature(vatTollMethod)
	VatTuneSignature            = GetLogNoteSignature(vatTuneMethod)
	VowFlogSignature            = GetLogNoteSignature(vowFlogMethod)
)
